import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
from termcolor import colored, cprint

def get(url):
    global user_agent
    user_agent = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36',
    }
    return requests.get(url, allow_redirects=False, headers=user_agent, verify=False)

def detectedAlert(msg='', file_out=None):
    if file_out:
        file_out.write(msg+'\n')
    print (colored('    '+msg, 'cyan'))


def wordPressDetector(url, file_out=None):
    wpLoginCheck = get(url + '/wp-login.php')
    if wpLoginCheck.status_code == 200 and "user_login" in wpLoginCheck.text and "404" not in wpLoginCheck.text:
        detectedAlert("[+] Detected: Potential WordPress WP-Login page: " + url + 'wp-login.php', file_out)
        return True

    wpAdminCheck = get(url + '/wp-admin')
    if wpAdminCheck.status_code == 200 and "user_login" in wpAdminCheck.text and "404" not in wpAdminCheck.text:
        detectedAlert("[+] Detected: Potential WordPress WP-Admin page: " + url + 'wp-admin.php', file_out)
        return True
    
    wpAdminUpgradeCheck = get(url + '/wp-admin/upgrade.php')
    if wpAdminCheck.status_code == 200 and "user_login" in wpAdminUpgradeCheck.text and "404" not in wpAdminUpgradeCheck.text:
        detectedAlert("[+] Detected: Potential WordPress WP-Admin page: " + url + 'wp-admin/upgrade.php', file_out)
        return True
    
    wpLinksCheck = get(url)
    if 'wp-' in wpLinksCheck.text:
        detectedAlert("[+] Detected: Potential WordPress wp- style links detected on index", file_out)
        return True
    
    wpAdminReadMeCheck = get(url + '/readme.html')
    if wpAdminReadMeCheck.status_code == 200 and "404" not in wpAdminReadMeCheck.text:
        detectedAlert("[+] Detected: Potential WordPress Readme.html: " + url + 'readme.html', file_out)
        return True


    joomlaDetector(url, file_out)
    return False
        
def joomlaDetector(url, file_out=None):
    joomlaAdminCheck = get(url + '/administrator/')
    if joomlaAdminCheck.status_code == 200 and "mod-login-username" in joomlaAdminCheck.text and "404" not in joomlaAdminCheck.text:
        detectedAlert("[+] Detected: Potential Joomla administrator page: " + url + 'administrator', file_out)
        return True
    
    joomlaTagCheck = get(url)
    if joomlaTagCheck.status_code == 200 and 'name="generator" content="Joomla' in joomlaTagCheck.text and "404" not in joomlaTagCheck.text:
        detectedAlert("[+] Detected: Potential Generated by Joomla tag on index", file_out)
        return True

    joomlaStringCheck = get(url)
    if joomlaStringCheck.status_code == 200 and "joomla" in joomlaStringCheck.text and "404" not in joomlaStringCheck.text:
        detectedAlert("[+] Detected: Potential Joomla strings on index", file_out)
        return True
    
    joomlaReadMeCheck = get(url)
    if joomlaReadMeCheck.status_code == 200 and "joomla" in joomlaReadMeCheck.text and "404" not in joomlaReadMeCheck.text:
        detectedAlert("[+] Detected: Potential Joomla Readme.txt: " + url + '/readme.txt', file_out)
        return True
    
    joomlaDirCheck = get(url+'/media/com_joomlaupdate/')
    if joomlaDirCheck.status_code == 403 and "404" not in joomlaDirCheck.text:
        detectedAlert("[+] Detected: Potential Joomla media/com_joomlaupdate directories: " + url + '/media/com_joomlaupdate/', file_out)
        return True
    drupalDetector(url, file_out)
    return False

def drupalDetector(url, file_out=None):
    drupalReadMeCheck = get(url + '/readme.txt')
    if drupalReadMeCheck.status_code == 200 and 'drupal' in drupalReadMeCheck.text and '404' not in drupalReadMeCheck.text:
        detectedAlert("[!] Detected: Potential Drupal Readme.txt: " + url + '/readme.txt', file_out)
        return True

    drupalTagCheck = get(url)
    if drupalTagCheck.status_code == 200 and 'name="Generator" content="Drupal' in drupalTagCheck.text:
        detectedAlert("[!] Detected: Potential Generated by Drupal tag on index", file_out)
        return True
    
    drupalCopyrightCheck = get(url + '/core/COPYRIGHT.txt')
    if drupalCopyrightCheck.status_code == 200 and 'Drupal' in drupalCopyrightCheck.text and '404' not in drupalCopyrightCheck.text:
        detectedAlert("[!] Detected: Potential Drupal COPYRIGHT.txt: " + url + '/core/COPYRIGHT.txt', file_out)
        return True
    
    drupalReadme2Check = get(url + '/modules/README.txt')
    if drupalReadme2Check.status_code == 200 and 'drupal' in drupalReadme2Check.text and '404' not in drupalReadme2Check.text:
        detectedAlert("[!] Detected: Potential Drupal modules/README.txt: " + url + '/modules/README.txt', file_out)
        return True
    
    drupalStringCheck = get(url)
    if drupalStringCheck.status_code == 200 and 'drupal' in drupalStringCheck.text:
        detectedAlert("[!] Detected: Potential Drupal strings on index", file_out)
        return True
    
    detectedAlert("[x] No CMS detected", file_out)
    return False


def runCmsDetector(url='', file_out=None):
    if url != '':
        print("    [?] Trying to detect CMS",url)
        wordPressDetector(url, file_out=file_out)

        
