# version.py

# This file is automatically generated
# Do not edit this file manually

__version__ = "1.0.0"
VERSION = __version__

# Individual version components
VERSION_MAJOR = 1
VERSION_MINOR = 2
VERSION_PATCH = 3
VERSION_PRE = None  # e.g., "alpha", "beta", "rc1"

# For compatibility checks
version_info = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)

# Full version including any pre-release suffix
VERSION_FULL = __version__

# Build identifier (e.g. git commit hash)
BUILD_ID = "a1b2c3d"

def get_version():
    """Returns the current version as a string."""
    return __version__

def get_version_info():
    """Returns the current version as a tuple."""
    return version_info

def is_compatible(required_version):
    """Check if current version is compatible with required_version."""
    req_major, req_minor, req_patch = map(int, required_version.split('.'))
    
    # Major version must match exactly
    if VERSION_MAJOR != req_major:
        return False
    
    # Current minor version must be >= required minor version
    if VERSION_MINOR < req_minor:
        return False
    
    # If minor versions match, current patch must be >= required patch
    if VERSION_MINOR == req_minor and VERSION_PATCH < req_patch:
        return False
    
    return True